FROM ubuntu:18.04

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update && apt-get install -y \
    xfce4 xfce4-goodies xfce4-terminal tightvncserver wget curl gnupg2 sudo icedtea-netx \
    libasound2 libgtk2.0-0 libdbus-glib-1-2 libxt6 libxss1 libnss3 libxrender1 libxcomposite1 \
    xserver-xorg-video-dummy x11-xserver-utils && apt-get clean

# Create a user
RUN useradd -m -s /bin/bash docker && echo "docker:docker" | chpasswd && adduser docker sudo

# Create Firefox shotcut
RUN mkdir -p /home/docker/.icons /home/docker/Desktop
COPY firefox.png /home/docker/.icons
COPY firefox.desktop /home/docker/Desktop
RUN chmod +x /home/docker/Desktop/firefox.desktop
RUN chown -R docker:docker /home/docker/

# Change Xconfig
COPY xorg.conf /etc/X11/xorg.conf

USER docker
WORKDIR /home/docker

# Set up VNC
RUN mkdir -p /home/docker/.vnc && \
    echo "docker" | vncpasswd -f > /home/docker/.vnc/passwd && \
    chmod 600 /home/docker/.vnc/passwd && \
    echo '#!/bin/sh\nstartxfce4 &' > /home/docker/.vnc/xstartup && \
    chmod +x /home/docker/.vnc/xstartup

# Download and install Firefox 52 ESR manually
RUN mkdir -p /home/docker/firefox52 && \
    wget -qO- https://ftp.mozilla.org/pub/firefox/releases/52.9.0esr/linux-x86_64/en-US/firefox-52.9.0esr.tar.bz2 \
    | tar -xj -C /home/docker/firefox52 --strip-components=1

# Set USER env var for VNC
ENV USER=docker

# Set PATH to use our Firefox build
ENV PATH="/home/docker/firefox52:${PATH}"

# Copy Oracle JRE tarball into image
#COPY jre-8u202-linux-x64.tar.gz /tmp/
COPY jdk-8u202-linux-x64.tar.gz /tmp/

# Extract it and set up environment
#RUN tar -xzf /tmp/jre-8u202-linux-x64.tar.gz -C /tmp
RUN tar -xzf /tmp/jdk-8u202-linux-x64.tar.gz -C /tmp

#ENV JAVA_HOME=/tmp/jre1.8.0_202/
ENV JAVA_HOME=/tmp/jdk1.8.0_202/jre/
ENV PATH=$JAVA_HOME/bin:$PATH

# Create plugin directory and symlink
RUN mkdir -p /home/docker/.mozilla/plugins \
    && ln -s $JAVA_HOME/lib/amd64/libnpjp2.so /home/docker/.mozilla/plugins/libnpjp2.so

# Expose VNC port
EXPOSE 5901

# Start VNC server safely and keep container alive
CMD bash -c "rm -f /tmp/.X1-lock /tmp/.X11-unix/X1 && vncserver :1 -geometry 1280x800 -depth 24 && tail -F /home/docker/.vnc/*.log"
